services:
  astro-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: EaseIP-com
    ports:
      - "4332:4323"
    restart: unless-stopped
    networks:
      - frontend
    environment:
      - USE_CLOUDFLARE=false
      - NODE_ENV=production
      - SITE_URL=https://easeip.induslevel.com

networks:
  frontend:
    external: true
